spring.application.name=smartOffice
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=smart_office

spring.datasource.username=postgres
spring.datasource.password=keyhes567

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true